import { Collection, Role } from "@neurofence/contracts/types";

export const fields: Partial<Record<Collection, string[]>> = {
  workforce: [
    "name",
    "app",
    "user",
    "instance",
    "activity",
    "classification",
    "device",
  ],
  providers: ["name", "type", "region", "secret", "endpoint"],
  models: [
    "name",
    "provider",
    "region",
    "capabilities",
    "inputRate",
    "outputRate",
  ],
  projects: [
    "name",
    "owner",
    "route",
    "budget",
    "policy",
    "costCenter",
    "keyExpires",
  ],
  routes: [
    "name",
    "alias",
    "primary",
    "fallback",
    "threshold",
    "retries",
    "region",
  ],
  policies: [
    "name",
    "pii",
    "injection",
    "region",
    "response",
    "responseAction",
    "streaming",
    "maxTokens",
    "detectors",
    "mode",
  ],
  budgets: [
    "name",
    "parent",
    "limit",
    "hard",
    "currency",
    "period",
    "threshold",
    "action",
    "fallback",
    "rpm",
    "tokens",
    "concurrency",
  ],
  agents: [
    "name",
    "owner",
    "purpose",
    "project",
    "allowedTools",
    "dataScope",
    "environment",
    "maxSteps",
    "maxDuration",
    "maxDepth",
    "maxCost",
    "maxModelCalls",
    "allowedModels",
    "allowedDelegates",
  ],
  servers: ["name", "endpoint", "transport", "auth", "secret", "owner"],
  tools: ["name", "serverId", "action", "scope", "parameters", "expires"],
  assets: [
    "name",
    "type",
    "owner",
    "risk",
    "coverage",
    "classification",
    "tags",
    "links",
    "status",
  ],
  workforcePolicies: [
    "name",
    "instance",
    "activity",
    "action",
    "justification",
  ],
  exceptions: ["name", "resource", "reason", "expires", "scope"],
  campaigns: ["name", "target", "pack", "schedule", "gate"],
  scans: ["name", "target", "artifact", "provenance", "gate"],
  integrations: ["name", "type", "endpoint", "secret"],
  members: ["name", "email", "role"],
  savedViews: [
    "name",
    "page",
    "query",
    "filter",
    "columns",
    "sort",
    "direction",
  ],
};

export const configCollections: Collection[] = [
  "policies",
  "routes",
  "budgets",
];

export const moduleFor: Partial<Record<Collection, string>> = {
  prices: "M6",
  controls: "M9",
  distributions: "M9",
  providers: "M4",
  models: "M4",
  projects: "M4",
  routes: "M4",
  policies: "M3",
  budgets: "M6",
  agents: "M5",
  servers: "M5",
  tools: "M5",
  assets: "M1",
  workforce: "M2",
  workforcePolicies: "M2",
  campaigns: "M7",
  scans: "M8",
  detectors: "M3",
};

export const ownRoles: Role[] = ["Developer", "Agent owner"];
