export const journeys = [
  [
    "Onboard a native provider",
    "Validate a connection, discover models, approve deployments and publish the catalog.",
    "gateway",
    "Providers & models",
    "Platform admin",
  ],
  [
    "Create governed application access",
    "Bind a published route, policy and budget; issue a key and test the application.",
    "gateway",
    "Applications & keys",
    "Platform engineer",
  ],
  [
    "Publish a guardrail",
    "Create a draft, simulate, request independent review, canary and publish.",
    "guardrails",
    "Policy builder",
    "Security admin",
  ],
  [
    "Register and scope an agent",
    "Declare its purpose, owner, application, tools and workflow limits.",
    "agents",
    "Agents",
    "Agent owner",
  ],
  [
    "Approve a tool request",
    "Review exact arguments, scope and expiry; approve and explicitly rerun once.",
    "governance",
    "Approvals",
    "Security admin",
  ],
  [
    "Set a hierarchical budget",
    "Create a child budget, configure limits and actions, review and publish.",
    "budgets",
    "Budget hierarchy",
    "FinOps owner",
  ],
  [
    "Investigate an AI incident",
    "Inspect the trace, assign a reviewer, contain access, resolve and export evidence.",
    "incidents",
    "",
    "SOC analyst",
  ],
  [
    "Manage workforce AI activity",
    "Review the account instance and activity; apply coaching or blocking and request an exception.",
    "workforce",
    "Activity",
    "Security admin",
  ],
  [
    "Run an assurance release gate",
    "Run a campaign, inspect findings, link remediation, retest and release.",
    "assurance",
    "Red team",
    "Security admin",
  ],
];
