export const navigation = [
  {
    id: "company",
    label: "Company administration",
    icon: "people",
    module: "M9",
    tabs: [
      "Overview",
      "People & teams",
      "Configuration",
      "Access & identity",
      "History & audit",
      "Provisioning",
    ],
  },
  {
    id: "overview",
    label: "Command center",
    icon: "grid",
    module: "M1",
    tabs: [],
  },
  {
    id: "inventory",
    label: "AI inventory",
    icon: "layers",
    module: "M1",
    tabs: ["Inventory", "Relationships", "Discovery & risk"],
  },
  {
    id: "workforce",
    label: "Workforce AI",
    icon: "people",
    module: "M2",
    tabs: ["Activity", "Policies"],
  },
  {
    id: "gateway",
    label: "AI gateway",
    icon: "route",
    module: "M4",
    tabs: [
      "Overview",
      "Providers & models",
      "Model catalog",
      "Routes",
      "Applications & keys",
      "Traces",
      "Playground",
    ],
  },
  {
    id: "guardrails",
    label: "Guardrails",
    icon: "shield",
    module: "M3",
    tabs: ["Overview", "Policy builder", "Simulator", "Detectors"],
  },
  {
    id: "agents",
    label: "Agents & MCP",
    icon: "bot",
    module: "M5",
    tabs: [
      "Agents",
      "MCP catalog",
      "Tool permissions",
      "Tool playground",
      "Tool traces",
      "Workflows & delegation",
    ],
  },
  {
    id: "budgets",
    label: "FinOps",
    icon: "wallet",
    module: "M6",
    tabs: [
      "Overview",
      "Budget hierarchy",
      "Usage ledger",
      "Forecast & anomalies",
      "Prices & reconciliation",
    ],
  },
  {
    id: "incidents",
    label: "Incidents",
    icon: "alert",
    module: "M9",
    tabs: [],
  },
  {
    id: "assurance",
    label: "Assurance",
    icon: "flask",
    module: "M7",
    tabs: ["Red team", "Supply chain", "Schedules & provenance"],
  },
  {
    id: "governance",
    label: "Governance",
    icon: "settings",
    module: "M9",
    tabs: [
      "Approvals",
      "Exceptions",
      "Evidence & compliance",
      "Evidence lifecycle",
      "Policy distribution",
      "Audit trail",
      "Integrations",
      "Members",
      "Settings",
      "Roles",
    ],
  },
];
