export const navigation = [
  {
    id: "company",
    description: "Manage people, defaults and access across your company.",
    label: "Company administration",
    icon: "people",
    module: "M9",
    tabs: [
      "Overview",
      "People & teams",
      "Configuration",
      "Access & identity",
      "History & audit",
      "Provisioning",
    ],
  },
  {
    id: "demo",
    description: "Create repeatable scenarios and save your demo work.",
    label: "Demo studio",
    icon: "flask",
    module: "M9",
    tabs: ["Scenarios", "Backup & restore"],
  },
  {
    id: "overview",
    description: "Your AI estate, decisions and priorities at a glance.",
    label: "Command center",
    icon: "grid",
    module: "M1",
    tabs: [],
  },
  {
    id: "inventory",
    description:
      "Understand ownership, dependencies and risk across your AI estate.",
    label: "AI inventory",
    icon: "layers",
    module: "M1",
    tabs: ["Inventory", "Relationships", "Discovery & risk"],
  },
  {
    id: "workforce",
    description: "Review workforce AI activity and protection policies.",
    label: "Workforce AI",
    icon: "people",
    module: "M2",
    tabs: ["Activity", "Policies"],
  },
  {
    id: "gateway",
    description: "Connect applications to governed model access.",
    label: "AI gateway",
    icon: "route",
    module: "M4",
    tabs: [
      "Overview",
      "Providers & models",
      "Model catalog",
      "Routes",
      "Applications & keys",
      "Traces",
      "Playground",
    ],
  },
  {
    id: "guardrails",
    description: "Build, inspect and test the controls around AI interactions.",
    label: "Guardrails",
    icon: "shield",
    module: "M3",
    tabs: ["Overview", "Policy builder", "Simulator", "Test lab", "Detectors"],
  },
  {
    id: "agents",
    description: "Control agent authority, tools and delegated workflows.",
    label: "Agents & MCP",
    icon: "bot",
    module: "M5",
    tabs: [
      "Agents",
      "MCP catalog",
      "Tool permissions",
      "Tool playground",
      "Tool traces",
      "Workflows & delegation",
    ],
  },
  {
    id: "budgets",
    description: "Track usage, allocate costs and manage budget controls.",
    label: "FinOps",
    icon: "wallet",
    module: "M6",
    tabs: [
      "Overview",
      "Budget hierarchy",
      "Usage ledger",
      "Forecast & anomalies",
      "Prices & reconciliation",
    ],
  },
  {
    id: "incidents",
    description: "Investigate events and coordinate a response.",
    label: "Incidents",
    icon: "alert",
    module: "M9",
    tabs: [],
  },
  {
    id: "assurance",
    description: "Test controls and track remediation evidence.",
    label: "Assurance",
    icon: "flask",
    module: "M7",
    tabs: ["Red team", "Supply chain", "Schedules & provenance"],
  },
  {
    id: "governance",
    description: "Review changes, manage evidence and verify distribution.",
    label: "Governance",
    icon: "settings",
    module: "M9",
    tabs: [
      "Approvals",
      "Exceptions",
      "Evidence & compliance",
      "Evidence lifecycle",
      "Policy distribution",
      "Audit trail",
      "Integrations",
      "Members",
      "Settings",
      "Roles",
    ],
  },
];

export type NavigationItem = (typeof navigation)[number];
