const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');

const root = path.resolve(__dirname, '..');
const resultsDir = path.join(root, 'test-results');
fs.mkdirSync(resultsDir, { recursive: true });
const completed = [], errors = [];
const check = (value, message) => { assert.ok(value, message); completed.push(message); };
let browser;

(async () => {
  browser = await chromium.launch({
    headless: true,
    ...(process.env.NEUROFENCE_BROWSER_PATH ? { executablePath: process.env.NEUROFENCE_BROWSER_PATH } : {}),
    ...(process.env.NEUROFENCE_SOFTWARE_RENDERING === '1' ? { args: ['--disable-dev-shm-usage', '--disable-gpu', '--disable-software-rasterizer', '--disable-features=Vulkan', '--use-gl=disabled'] } : {}),
  });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true, reducedMotion: 'reduce' });
  const page = await context.newPage();
  page.setDefaultTimeout(8000);
  page.on('pageerror', e => errors.push(e.message));
  const url = pathToFileURL(path.join(root, 'index.html')).href;
  const action = name => page.locator(`[data-action="${name}"]`);
  const nav = async (name, tab) => { await page.locator(`#sidebar [data-page="${name}"]`).click(); if (tab) await page.getByRole('tab', { name: tab, exact: true }).click(); };
  const role = name => page.locator('#role-preview').selectOption(name);
  const submit = name => page.locator(`form[data-form="${name}"] button[type="submit"]`).click();
  const close = () => page.getByLabel('Close dialog', { exact: true }).click();
  const open = (type, id) => page.locator(`[data-action="${type}"][data-id="${id}"]`).first().click();
  const trace = () => page.evaluate(() => state.traces[0]);
  const editAgent = async id => { await nav('agents', 'Agents'); await open('agent', id); await action('edit-agent').click(); };
  const runTool = async (id, tool) => { await nav('agents', 'Tool playground'); await page.locator('#sim-agent').selectOption(id); await page.locator('#sim-tool').selectOption(tool); await submit('tool-run'); return trace(); };
  const screenshot = name => page.screenshot({ path: path.join(resultsDir, name + '.jpg'), type: 'jpeg', quality: 88, style: '#toasts { visibility: hidden; }' });
  await page.goto(url);

  // Emulate the shape of a previously saved v0.2 browser dataset.
  await page.evaluate(() => {
    const old = seed();
    old.projects[0].name = 'Saved claims copilot';
    old.traces.forEach(t => { delete t.budgetScope; delete t.budgetAttribution; });
    old.agents.forEach(a => delete a.allowedTools);
    localStorage.setItem(STORAGE, JSON.stringify(old));
  });
  await page.reload();
  check(await page.evaluate(() => state.projects[0].name === 'Saved claims copilot' && state.traces.length === 64 && state.traces.every(t => t.budgetScope && t.budgetAttribution === 'legacy-binding')), 'Legacy browser records gain budget attribution without losing saved data');
  check(await page.evaluate(() => state.agents.find(a => a.id === 'finance-agent').allowedTools.includes('vendor.updateBankAccount') && !state.agents.find(a => a.id === 'claims-agent').allowedTools.includes('vendor.updateBankAccount')), 'Legacy agents receive explicit compatible tool permissions');

  const before = await page.evaluate(() => ({ claims: spent('b-claims'), support: spent('b-support'), total: spent('org'), key: state.projects[0].key }));
  await nav('gateway', 'Applications & keys');
  await open('project', 'claims');
  await action('edit-project').click();
  await page.locator('#project-name').fill('Cancelled edit');
  await close();
  check(await page.evaluate(() => state.projects[0].name === 'Saved claims copilot'), 'Cancelling an application edit leaves the record unchanged');
  await open('project', 'claims');
  await action('edit-project').click();
  await page.locator('#project-name').fill(await page.evaluate(() => state.projects.find(p => p.id === 'finance').name));
  await submit('project-edit');
  check((await page.locator('.form-error').innerText()).includes('already exists'), 'Application edits reject duplicate names');
  await page.locator('#project-name').fill('Claims operations copilot');
  await page.locator('#project-budget').selectOption('b-support');
  await screenshot('application-editor');
  await submit('project-edit');
  check(await page.evaluate(() => state.projects[0].name === 'Claims operations copilot' && state.projects[0].budget === 'b-support'), 'Application editing saves name and budget binding');
  assert.deepEqual(await page.evaluate(() => ({ claims: spent('b-claims'), support: spent('b-support'), total: spent('org'), key: state.projects[0].key })), before);
  check(true, 'Rebinding an application preserves historical charges and its existing credential');
  await action('test-project').click();
  await submit('model-run');
  const request = await trace();
  check(request.executed && request.cost > 0 && request.budgetScope === 'b-support', 'A subsequent model request charges the newly selected budget');
  check(await page.evaluate(({before, cost}) => spent('b-claims') === before.claims && spent('b-support') === round(before.support + cost), {before, cost: request.cost}), 'The old budget keeps its spend while only the new budget receives the new charge');
  await nav('budgets', 'Usage ledger');
  const pendingUsage = page.waitForEvent('download');
  await action('export-usage').click();
  const usage = JSON.parse(fs.readFileSync(await (await pendingUsage).path(), 'utf8'));
  check(usage.usage[0].budgetScope === 'b-support' && usage.usage[0].budgetAttribution === 'request', 'Usage exports include the budget charged at request time');
  await page.reload();
  check(await page.evaluate(value => spent('b-claims') === value && state.projects[0].budget === 'b-support', before.claims), 'Budget attribution remains stable after reloading an edited application');

  await role('Developer');
  await nav('gateway', 'Applications & keys');
  await open('project', 'finance');
  check(await action('edit-project').isDisabled(), 'Developer cannot edit another owner’s application');
  await close();
  await open('project', 'claims');
  await action('edit-project').click();
  check(await page.locator('#project-owner').getAttribute('readonly') !== null, 'Developer ownership cannot be reassigned through application editing');
  await close();
  await nav('agents', 'Agents');
  await open('agent', 'finance-agent');
  check(await action('edit-agent').isDisabled(), 'Developer cannot edit another owner’s agent');
  await close();
  await role('Auditor');
  await open('agent', 'claims-agent');
  check(await action('edit-agent').isDisabled(), 'Auditor agent access stays read-only');
  await close();
  await role('Platform admin');

  await editAgent('claims-agent');
  await page.locator('#agent-purpose').fill('Retrieve approved guidance for claims reviewers.');
  await page.locator('#agent-steps').fill('2');
  await page.locator('input[name="agent-tools"][value="claims.read"]').uncheck();
  check(await page.locator('input[name="agent-tools"][value="claims.delete"]').isDisabled(), 'The globally blocked tool cannot be granted in the agent editor');
  await screenshot('agent-editor');
  await submit('agent-edit');
  check(await page.evaluate(() => {const a=state.agents.find(a=>a.id==='claims-agent'); return a.maxSteps===2 && a.allowedTools.join(',')==='knowledge.search' && a.purpose.startsWith('Retrieve');}), 'Agent edit saves purpose, workflow cap and its explicit tool list');
  await close();
  let t = await runTool('claims-agent', 'claims.read');
  check(t.decision === 'DENY' && !t.executed && t.cost === 0 && t.reason.includes('not granted'), 'Removing a grant blocks the next tool call before execution and cost');
  t = await runTool('claims-agent', 'knowledge.search');
  check(t.executed && t.budgetScope === 'b-support', 'A granted read tool executes within the application’s updated budget');
  await editAgent('claims-agent');
  await page.locator('input[name="agent-tools"][value="knowledge.search"]').uncheck();
  await submit('agent-edit');
  await close();
  t = await runTool('claims-agent', 'knowledge.search');
  check(t.decision === 'DENY' && !t.executed, 'Saving an empty grant list denies every otherwise allowed tool');
  await page.reload();
  check(await page.evaluate(() => state.agents.find(a => a.id === 'claims-agent').allowedTools.length === 0), 'An explicitly empty grant list survives reload without migration restoring access');
  await editAgent('claims-agent');
  await page.locator('input[name="agent-tools"][value="vendor.updateBankAccount"]').check();
  await submit('agent-edit');
  check((await page.locator('.form-error').innerText()).includes('Finance application'), 'A financial write grant cannot be attached to a non-finance application');
  await close();

  t = await runTool('finance-agent', 'vendor.updateBankAccount');
  const oldApproval = t.approvalId;
  await open('approval', oldApproval);
  await action('preview-reviewer').click();
  await page.locator('#approval-reason').fill('Verified the exact sample vendor and account reference.');
  await action('approve-approval').click();
  await close();
  await role('Platform admin');
  await editAgent('finance-agent');
  await page.locator('input[name="agent-tools"][value="vendor.updateBankAccount"]').uncheck();
  await submit('agent-edit');
  check(await page.evaluate(id => state.approvals.find(a => a.id === id).status === 'Cancelled', oldApproval), 'Changing agent grants cancels an already approved but unused request');
  await close();
  await editAgent('finance-agent');
  await page.locator('input[name="agent-tools"][value="vendor.updateBankAccount"]').check();
  await submit('agent-edit');
  await close();
  t = await runTool('finance-agent', 'vendor.updateBankAccount');
  check(t.decision === 'REQUIRE_APPROVAL' && t.approvalId !== oldApproval && !t.executed, 'Regranting a tool requires a new approval; an old approval cannot revive');
  const bindingApproval = t.approvalId;
  await nav('gateway', 'Applications & keys');
  await open('project', 'finance');
  await action('edit-project').click();
  await page.locator('#project-owner').fill('Priya Shah');
  await submit('project-edit');
  check(await page.evaluate(id => state.approvals.find(a => a.id === id).status === 'Cancelled', bindingApproval), 'Application access edits invalidate approvals of its dependent agents');
  await close();
  await nav('gateway', 'Applications & keys');
  await open('project', 'claims');
  await action('edit-project').click();
  await page.locator('#project-owner').fill('Mira Kapoor');
  await submit('project-edit');
  await close();
  await role('Developer');
  t = await runTool('claims-agent', 'knowledge.search');
  check(t.decision === 'DENY' && t.reason.includes('scope'), 'A Developer loses runtime access when the owning application moves out of scope');
  const oldWorkflow = await page.evaluate(() => state.agents.find(a => a.id === 'claims-agent').workflow);
  await action('new-workflow').click();
  check(await page.evaluate(w => state.agents.find(a => a.id === 'claims-agent').workflow === w, oldWorkflow), 'An out-of-scope Developer cannot reset that agent’s workflow');

  await role('Auditor');
  await nav('incidents');
  await open('incident', 'INC-1042');
  check(await page.locator('form[data-form="incident-save"]').count() === 0 && await action('export-incident').isEnabled(), 'Auditor can inspect and export incident evidence without editing');
  await action('preview-incident-reviewer').click();
  await submit('incident-save');
  check((await page.locator('.form-error').innerText()).includes('Change the owner or add a note'), 'An empty incident review is not recorded as a response action');
  await page.locator('#incident-owner').fill('Mira Kapoor');
  await page.locator('#incident-note').fill('Investigating the blocked destructive operation.');
  await submit('incident-save');
  check(await page.evaluate(() => {const i=state.incidents.find(i=>i.id==='INC-1042'); return i.status==='Open' && i.owner==='Mira Kapoor' && i.notes.some(n=>n.kind==='Investigation note' && n.actor && n.ts);}), 'Assignment and timestamped notes save without resolving the incident');
  await page.locator('#incident-note').fill('<img src=x onerror="window.unsafeReview=true"> review text');
  await submit('incident-save');
  check(await page.locator('.event img').count() === 0 && !(await page.evaluate(() => window.unsafeReview)), 'User-authored review text is displayed as text rather than executable markup');
  await action('contain-incident').click();
  await action('confirm-contain').click();
  await action('resolve-incident').click();
  check((await page.locator('.form-error').innerText()).includes('note before resolving'), 'Incident resolution requires an investigation reason');
  await page.locator('#incident-note').fill('Contained the agent and verified that further calls are denied.');
  await action('resolve-incident').click();
  await open('incident', 'INC-1042');
  await action('reopen-incident').click();
  check((await page.locator('.form-error').innerText()).includes('reason before reopening'), 'Reopening a resolved incident requires a reason');
  await page.locator('#incident-note').fill('Follow up with the application owner before restoring access.');
  await action('reopen-incident').click();
  check(await page.evaluate(() => state.incidents.find(i=>i.id==='INC-1042').status==='Open' && state.agents.find(a=>a.id==='claims-agent').status==='Suspended'), 'Reopening restores the finding to Open while retaining agent containment');
  const pendingEvidence = page.waitForEvent('download');
  await action('export-incident').click();
  const evidence = JSON.parse(fs.readFileSync(await (await pendingEvidence).path(), 'utf8'));
  check(evidence.prototype && evidence.incident.id === 'INC-1042' && evidence.incident.notes.some(n=>n.kind==='Reopened') && evidence.trace.id === evidence.incident.trace && evidence.agent.status === 'Suspended' && evidence.audit.length >= 4, 'Individual incident export bundles linked trace, response history, agent state and audit entries');
  await screenshot('incident-review');
  await close();
  await page.reload();
  await open('incident', 'INC-1042');
  check((await page.locator('.dialog-content').innerText()).includes('Follow up with the application owner'), 'Incident ownership and review history survive reload');
  await close();

  const phoneContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce', acceptDownloads: true });
  const phone = await phoneContext.newPage();
  phone.on('pageerror', e => errors.push(e.message));
  await phone.goto(url);
  await phone.locator('#mobile-nav [data-page="gateway"]').tap();
  await phone.getByRole('tab', {name:'Applications & keys',exact:true}).tap();
  await phone.locator('[data-action="project"][data-id="claims"]').first().tap();
  await phone.locator('[data-action="edit-project"]').tap();
  await phone.locator('#project-name').fill('Mobile claims copilot');
  await phone.locator('form[data-form="project-edit"] button[type="submit"]').tap();
  check(await phone.evaluate(() => state.projects[0].name === 'Mobile claims copilot'), 'Application editing works through the mobile navigation and sheet');
  await phone.getByLabel('Close dialog', {exact:true}).tap();
  await phone.locator('#mobile-nav [data-page="agents"]').tap();
  await phone.locator('[data-action="agent"][data-id="claims-agent"]').first().tap();
  await phone.locator('[data-action="edit-agent"]').tap();
  await phone.locator('input[name="agent-tools"][value="claims.read"]').uncheck();
  await phone.locator('form[data-form="agent-edit"] button[type="submit"]').tap();
  check(await phone.evaluate(() => !state.agents[0].allowedTools.includes('claims.read')), 'Agent grant editing is functional on the mobile sheet');
  await phone.getByLabel('Close dialog', {exact:true}).tap();
  await phone.getByRole('button', {name:'More navigation'}).tap();
  await phone.locator('#sidebar [data-page="incidents"]').tap();
  await phone.locator('[data-action="incident"][data-id="INC-1042"]').first().tap();
  await phone.locator('[data-action="preview-incident-reviewer"]').tap();
  await phone.locator('#incident-note').fill('Reviewed from the phone prototype.');
  await phone.locator('form[data-form="incident-save"] button[type="submit"]').tap();
  check(await phone.evaluate(() => state.incidents[0].notes.some(n => n.text === 'Reviewed from the phone prototype.')), 'Mobile reviewer switching and note saving update the shared incident record');
  await phone.screenshot({ path:path.join(resultsDir,'mobile-incident-review.jpg'),type:'jpeg',quality:88,style:'#toasts {visibility:hidden;}' });
  const overflows=[];
  for (const width of [320,390,768,1440]) {
    await page.setViewportSize({width,height:900});
    for (const view of ['project-edit','agent-edit','incident']) {
      await page.evaluate(view => {
        ui.role = view === 'incident' ? 'Security admin' : 'Platform admin';
        if (view === 'project-edit') newProject('claims');
        else if (view === 'agent-edit') newAgent('finance-agent');
        else incidentDialog('INC-1042');
      }, view);
      const excess = await page.evaluate(() => Math.max(document.documentElement.scrollWidth-innerWidth, ...[...document.querySelectorAll('.dialog,.dialog-content,form,.tool-grants')].map(el=>el.scrollWidth-el.clientWidth)));
      if (excess > 1) overflows.push({width,view,excess});
      await close();
    }
  }
  check(overflows.length === 0, 'New application, agent and incident sheets fit 320px through desktop: '+JSON.stringify(overflows));
  check(errors.length === 0, 'No uncaught browser errors in editing, migration and incident review');
  fs.writeFileSync(path.join(resultsDir,'lifecycle.json'),JSON.stringify({passed:completed.length,completed,errors},null,2));
  console.log(JSON.stringify({passed:completed.length,completed,errors},null,2));
  await browser.close();
})().catch(async error => {
  fs.writeFileSync(path.join(resultsDir,'lifecycle.json'),JSON.stringify({passed:completed.length,completed,errors,failure:error.message},null,2));
  console.error(JSON.stringify({completed,errors,failure:error.message},null,2));
  await browser?.close();
  process.exitCode=1;
});
