const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require('playwright');
const root = path.resolve(__dirname, '..');
const resultsDir = path.join(root, 'test-results');
fs.mkdirSync(resultsDir, { recursive: true });
let browser;
const completed = [];
const errors = [];
const check = (value, message) => { assert.ok(value, message); completed.push(message); };
(async () => {
  browser = await chromium.launch({
    headless: true,
    ...(process.env.NEUROFENCE_BROWSER_PATH ? { executablePath: process.env.NEUROFENCE_BROWSER_PATH } : {}),
    ...(process.env.NEUROFENCE_SOFTWARE_RENDERING === '1' ? { args: ['--disable-dev-shm-usage', '--disable-gpu', '--disable-software-rasterizer', '--disable-features=Vulkan', '--use-gl=disabled'] } : {})
  });
  const context = await browser.newContext({ viewport: { width:1440, height:1000 }, acceptDownloads:true, reducedMotion:'reduce' });
  const page = await context.newPage();
  page.setDefaultTimeout(10000);
  page.on('pageerror', e => errors.push(e.message));
  const action = (name) => page.locator(`[data-action="${name}"]`);
  const nav = async (name, tab) => { await page.locator(`#sidebar [data-page="${name}"]`).click(); if (tab) await page.getByRole('tab',{name:tab,exact:true}).click(); };
  const role = async (name) => page.locator('#role-preview').selectOption(name);
  const trace = async () => page.evaluate(() => state.traces[0]);
  const model = async (prompt) => { if(prompt) await page.locator('#sim-prompt').fill(prompt); await page.locator('#model-form button[type="submit"]').click(); return trace(); };
  const tool = async () => { await page.locator('#tool-form button[type="submit"]').click(); return trace(); };
  const close = async () => { if(await page.getByRole('dialog').count()) await page.getByLabel('Close dialog').click(); };
  await page.goto(pathToFileURL(path.join(root, 'index.html')).href);
  await action('reset-confirm').click(); await action('reset-demo').click();
  const screens={overview:[],inventory:[],workforce:[],gateway:['Overview','Providers & models','Routes','Applications & keys','Traces','Playground'],guardrails:['Overview','Policy builder','Simulator'],agents:['Agents','MCP catalog','Tool playground','Tool traces'],budgets:['Overview','Budget hierarchy','Usage ledger'],incidents:[],assurance:['Red team','Supply chain'],governance:['Approvals','Audit trail','Settings','Roles']};
  for (const [name,tabs] of Object.entries(screens)) {
    await nav(name);
    assert.equal(await page.locator('h1').count(),1,name);
    for (const tab of tabs) { await page.getByRole('tab',{name:tab,exact:true}).click(); assert.ok((await page.locator('#main').innerText()).length>100,tab); }
  }
  check(errors.length===0,'All 10 navigation areas and 22 tab views render without browser errors');
  await nav('inventory'); await page.locator('#page-search').fill('Claims');
  check(await page.locator('tbody tr').count()===4,'Inventory search filters matching assets');
  await page.locator('#page-search').fill('no-such-asset');
  check((await page.locator('tbody').innerText()).includes('No matching results'),'Empty search state works');
  await page.keyboard.press('Control+k'); await page.locator('#global-search').fill('Finance operations');
  await page.locator('.search-result').click();
  check((await page.locator('#dialog-title').innerText())==='Finance operations agent','Global search opens the selected asset'); await close();
  await nav('gateway','Playground');
  let t=await model('Summarise the approved claims handling guidelines.');
  check(t.decision==='ALLOW'&&t.executed&&t.cost>0,'Safe model request executes and records cost');
  await action('preset-pii').click(); t=await model();
  check(t.decision==='REDACT'&&t.executed&&!t.preview.includes('ABCDE1234F')&&!t.preview.includes('123456789012'),'Sensitive model input is redacted in trace evidence');
  await action('preset-injection').click(); t=await model();
  check(t.decision==='DENY'&&!t.executed&&t.cost===0,'Prompt injection stops before execution and creates no charge');
  await role('Auditor');
  check(await page.locator('#model-form button[type="submit"]').isDisabled(),'Auditor cannot run requests');
  await role('Developer'); await page.locator('#sim-project').selectOption('finance');
  t=await model('Summarise the approved guidelines.');
  check(t.decision==='DENY'&&!t.executed&&t.reason.includes('scope'),'Developer scope enforced at runtime');
  await role('Platform admin'); await page.locator('#sim-project').selectOption('claims');
  await nav('budgets','Budget hierarchy');
  await page.locator('[data-action="edit-budget"][data-id="org"]').last().click();
  await page.locator('#budget-limit').fill('0'); await page.getByRole('button',{name:'Save budget',exact:true}).click();
  await nav('gateway','Playground'); t=await model();
  check(t.decision==='DENY'&&!t.executed&&t.cost===0,'Parent hard budget blocks a call despite available child budget');
  await nav('overview');
  check(!(await page.locator('#main').innerText()).includes('Infinity'),'Zero budget renders a finite usage percentage');
  await nav('budgets','Budget hierarchy');await page.locator('[data-action="edit-budget"][data-id="org"]').last().click();
  await page.locator('#budget-limit').fill('1000');await page.getByRole('button',{name:'Save budget',exact:true}).click();
  await nav('gateway','Routes');await action('edit-route').click();
  await page.locator('#route-primary').selectOption('anthropic');await page.locator('form[data-form="route-save"] button[type="submit"]').click();
  await nav('gateway','Playground'); t=await model();
  check(t.decision==='ROUTE_ALTERNATE'&&t.executed&&t.provider==='vertex','Fallback obeys India residency when the primary is Global');
  await nav('gateway','Routes');await action('edit-route').click();await page.locator('#route-primary').selectOption('azure');await page.locator('form[data-form="route-save"] button[type="submit"]').click();
  await nav('agents','Tool playground'); t=await tool(); const approval=t.approvalId;
  check(t.decision==='REQUIRE_APPROVAL'&&!t.executed&&t.cost===0,'Financial write waits for human approval without execution');
  await tool();
  check(await page.evaluate(()=>state.approvals.length)===1,'Repeated pending request reuses its existing approval');
  await role('Security admin'); await action('approval').click();
  await page.locator('#approval-reason').fill('Verified the exact vendor and sample account reference.');
  await action('approve-approval').click();
  check(await page.evaluate(id=>state.approvals.find(a=>a.id===id).status,approval)==='Approved','Security review records approval');
  check(!(await trace()).executed,'Approving a tool request does not execute it');
  await action('resume-approved').click();await role('Platform admin');
  t=await tool();
  check(t.executed&&t.cost===0.08&&t.approvalId===approval,'Explicit rerun executes the exact approved tool call once');
  check(await page.evaluate(id=>state.approvals.find(a=>a.id===id).status,approval)==='Used','Approval is consumed by execution');
  t=await tool();
  check(!t.executed&&t.decision==='REQUIRE_APPROVAL'&&t.approvalId!==approval,'Second tool execution needs a new approval');
  await page.locator('#sim-args').fill(JSON.stringify({vendor_id:'VENDOR-999',account_ref:'demo-account-01'}));t=await tool();
  check(!t.executed&&t.decision==='DENY'&&t.reason.includes('scope'),'Changed vendor outside the tool scope is denied');
  await page.locator('#sim-tool').selectOption('claims.delete'); t=await tool();
  check(!t.executed&&t.cost===0&&t.decision==='DENY','Destructive tool is denied before execution');
  await action('new-workflow').click();
  check(await page.evaluate(()=>state.agents.find(a=>a.id==='finance-agent').stepsUsed)===0,'New workflow resets execution steps');
  await page.locator('#sim-tool').selectOption('vendor.updateBankAccount');t=await tool();
  const beforePolicy=t.approvalId;
  await role('Security admin');await nav('guardrails','Policy builder');
  await page.locator('#policy-pii').selectOption('block');await page.getByRole('button',{name:'Save draft',exact:true}).click();
  check(await page.evaluate(()=>state.policy.pii)==='redact','Saving a policy draft leaves the active policy unchanged');
  await page.getByRole('tab',{name:'Simulator',exact:true}).click();await page.locator('#guard-version').selectOption('draft');
  await page.locator('#guard-sim-form button[type="submit"]').click();
  check(await page.evaluate(()=>ui.guardResult.decision)==='DENY','Saved draft can be tested before publication');
  await page.getByRole('tab',{name:'Policy builder',exact:true}).click();await action('publish-policy').click();await action('confirm-publish').click();
  check(await page.evaluate(()=>state.policy.version===4&&state.policy.pii==='block'),'Publishing activates the next policy version');
  check(await page.evaluate(id=>state.approvals.find(a=>a.id===id).status,beforePolicy)==='Superseded','Policy publication invalidates outstanding approvals');
  await nav('gateway','Playground');t=await model('Return [demo:response-pii] for the demo.');
  check(t.decision==='DENY'&&t.executed&&t.cost>0&&t.output==='','Response block withholds output while retaining provider cost');
  await nav('guardrails','Policy builder');await action('policy-history').click();await action('rollback-policy').click();await action('confirm-rollback').click();
  check(await page.evaluate(()=>state.policy.version===5&&state.policy.pii==='redact'),'Rollback restores configuration as a new version');
  await nav('incidents');await page.locator('[data-action="incident"][data-id="INC-1042"]').last().click();
  await action('contain-incident').click();await action('confirm-contain').click();
  await page.locator('#incident-note').fill('Reviewed the blocked delete attempt and suspended the agent.');await action('resolve-incident').click();
  check(await page.evaluate(()=>state.agents.find(a=>a.id==='claims-agent').status==='Suspended'&&state.incidents.find(i=>i.id==='INC-1042').status==='Resolved'),'Incident containment and resolution update agent and evidence');
  await nav('agents','Tool playground');await page.locator('#sim-agent').selectOption('claims-agent');await page.locator('#sim-tool').selectOption('claims.read');t=await tool();
  check(t.decision==='DENY'&&!t.executed&&t.reason.includes('suspended'),'Contained agent cannot run subsequent tool calls');
  await role('Platform admin');await nav('gateway','Providers & models');await action('new-provider').click();
  await page.locator('#provider-name').fill('QA India deployment');await page.locator('form[data-form="provider-step"] button[type="submit"]').click();
  await page.locator('#provider-secret').fill('vault://demo/qa');await page.locator('form[data-form="provider-step"] button[type="submit"]').click();await action('provider-create').click();
  check(await page.evaluate(()=>state.providers.length)===5,'Three-step provider onboarding creates a sample connector');
  await page.getByRole('tab',{name:'Applications & keys',exact:true}).click();await action('new-project').click();
  await page.locator('#project-name').fill('Underwriting copilot');await page.locator('#project-owner').fill('Priya Shah');await page.locator('form[data-form="project-create"] button[type="submit"]').click();
  check(await page.evaluate(()=>state.projects.some(p=>p.name==='Underwriting copilot'&&p.key.startsWith('nf_demo_')&&p.route&&p.budget)),'Application creation binds route, budget and sample credential');await close();
  await nav('governance','Audit trail');const downloadPromise=page.waitForEvent('download');await action('export-audit').click();const download=await downloadPromise;
  const dlPath=await download.path();const events=JSON.parse(fs.readFileSync(dlPath,'utf8'));
  check(events.prototype&&events.events.length>20,'Audit export contains the actions performed in the prototype');
  await page.reload();
  check(await page.evaluate(()=>state.projects.length===4&&state.policy.version===5),'Changes persist after reloading the standalone HTML');
  await role('Security admin');await nav('assurance','Red team');await action('run-assurance').first().click();
  check(await page.evaluate(()=>state.assurance[0].results.every(r=>r.pass)),'Sample regression suite reflects the active policy');
  await role('Platform admin');await action('reset-confirm').click();await action('reset-demo').click();
  check(await page.evaluate(()=>state.projects.length===3&&state.approvals.length===0&&state.traces.length===64),'Reset restores the original demo fixture');
  await page.screenshot({path:path.join(resultsDir, 'overview.png'),fullPage:true, animations:'disabled'});
  await nav('gateway','Playground');await model('My PAN is ABCDE1234F. Summarise the claim.');
  await page.screenshot({path:path.join(resultsDir, 'playground.png'),fullPage:true, animations:'disabled'});
  await page.setViewportSize({width:375,height:812});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile playground fits a 375-pixel viewport');
  await page.screenshot({path:path.join(resultsDir, 'mobile-playground.png'),fullPage:true, animations:'disabled'});
  await action('toggle-nav').click();await nav('overview');
  check(await page.evaluate(()=>!document.body.classList.contains('nav-open')),'Mobile navigation opens, changes screens and closes');
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overview fits a 375-pixel viewport');
  await page.screenshot({path:path.join(resultsDir, 'mobile-overview.png'),fullPage:true, animations:'disabled'});
  check(errors.length===0,'No uncaught browser errors across the complete journeys');
  fs.writeFileSync(path.join(resultsDir, 'results.json'),JSON.stringify({passed:completed.length,completed,errors},null,2));
  console.log(JSON.stringify({passed:completed.length,completed,errors},null,2));
  await browser.close();
})().catch(async error => {
  fs.writeFileSync(path.join(resultsDir, 'results.json'), JSON.stringify({ passed: completed.length, completed, errors, failure: error.message }, null, 2));
  console.error(JSON.stringify({ completed, errors }, null, 2));
  console.error(error);
  await browser?.close();
  process.exitCode = 1;
});
