import { Collection, State } from "@neurofence/contracts/types";
import { Field } from "../../components/Fields";
import { resourceOptions } from "../../lib/resource-options";

export function fieldsFor(
  collection: Collection,
  state: State,
  user: string,
): Field[] {
  const name: Field = { key: "name", label: "Name", required: true },
    owner: Field = {
      key: "owner",
      label: "Owner",
      required: true,
      default: user,
    };
  const choice = (
    key: string,
    label: string,
    options: string[],
    value?: string,
  ): Field => ({
    key,
    label,
    type: "select",
    options,
    required: true,
    default: value || options[0],
  });
  const reference = (
    key: string,
    label: string,
    c: Collection,
    optional = false,
  ): Field => ({
    key,
    label,
    type: "select",
    options: resourceOptions(state, c),
    required: !optional,
    default: optional ? "" : state.data[c][0]?.id || "",
  });
  const count = (
    key: string,
    label: string,
    value: number,
    min = 1,
    max?: number,
  ): Field => ({
    key,
    label,
    type: "number",
    default: value,
    min,
    max,
    required: true,
  });
  const secret: Field = {
    key: "secret",
    label: "Secret reference",
    required: true,
    default: "vault://demo/connection",
    help: "Reference only. The demo never accepts or retrieves a provider secret.",
  };
  const schemas: Partial<Record<Collection, Field[]>> = {
    providers: [
      name,
      choice("type", "Native connector", [
        "Azure OpenAI",
        "OpenAI",
        "Anthropic",
        "AWS Bedrock",
        "Google Vertex AI",
        "Self-hosted",
      ]),
      choice("region", "Region", ["India Central", "India West", "Global"]),
      secret,
      { key: "endpoint", label: "Optional custom endpoint", default: "" },
    ],
    models: [
      name,
      reference("provider", "Provider", "providers"),
      choice("region", "Region", ["India Central", "India West", "Global"]),
      {
        key: "capabilities",
        label: "Capabilities",
        type: "multi",
        options: ["Chat", "Streaming", "Embeddings", "Responses", "Vision"],
        default: ["Chat"],
      },
      count("inputRate", "Input price per 1K tokens (INR)", 0.35, 0),
      count("outputRate", "Output price per 1K tokens (INR)", 0.9, 0),
    ],
    projects: [
      name,
      owner,
      reference("route", "Model route", "routes"),
      reference("policy", "Guardrail policy", "policies"),
      reference("budget", "Budget", "budgets"),
    ],
    routes: [
      name,
      {
        key: "alias",
        label: "Model alias",
        required: true,
        default: "governed-chat",
      },
      reference("primary", "Primary provider", "providers"),
      reference("fallback", "Fallback provider", "providers", true),
      count("threshold", "Use fallback below remaining budget (%)", 20, 0, 100),
      count("retries", "Maximum retries", 2, 0, 5),
      choice("region", "Residency constraint", ["India only", "Any region"]),
    ],
    policies: [
      name,
      choice("mode", "Enforcement mode", ["enforce", "monitor"]),
      choice("pii", "Sensitive input action", ["redact", "block", "monitor"]),
      choice("injection", "Prompt injection action", ["block", "monitor"]),
      choice("region", "Residency", ["India only", "Any region"]),
      {
        key: "response",
        label: "Inspect provider responses",
        type: "checkbox",
        default: true,
      },
      choice("responseAction", "Sensitive response action", [
        "redact",
        "block",
        "monitor",
      ]),
      choice("streaming", "Streaming mode", [
        "strict_buffered",
        "balanced_chunked",
        "posthoc_monitor",
      ]),
      count("maxTokens", "Maximum output tokens", 4096, 1, 32768),
      {
        key: "detectors",
        label: "Ordered detector pipeline",
        type: "ordered",
        options: resourceOptions(state, "detectors"),
        default: ["pii", "secrets", "injection"],
      },
    ],
    budgets: [
      name,
      reference("parent", "Parent budget", "budgets", true),
      count("limit", "Spend limit (INR)", 100, 0),
      {
        key: "hard",
        label: "Enforce as a hard limit",
        type: "checkbox",
        default: true,
      },
      choice("currency", "Ledger currency", ["INR"]),
      choice("period", "Budget period", ["Monthly", "Weekly", "Daily"]),
      count("threshold", "Alert threshold (%)", 80, 0, 100),
      choice("action", "Threshold action", [
        "Block",
        "Notify",
        "Throttle",
        "Route",
        "Require approval",
        "Circuit break",
      ]),
      reference("fallback", "Lower-cost provider", "providers", true),
      count("rpm", "Requests per minute", 120),
      count("tokens", "Tokens per minute", 100000),
      count("concurrency", "Concurrent requests", 10),
    ],
    agents: [
      name,
      owner,
      { key: "purpose", label: "Purpose", type: "textarea", required: true },
      reference("project", "Application", "projects"),
      choice("environment", "Environment", [
        "Development",
        "Staging",
        "Production",
      ]),
      {
        key: "dataScope",
        label: "Data scope",
        default: "Approved records",
        required: true,
      },
      {
        key: "allowedTools",
        label: "Requested tools",
        type: "multi",
        options: state.data.tools.map((t) => [t.id, `${t.name} · ${t.action}`]),
        default: [],
      },
      count("maxSteps", "Workflow call limit", 20),
      count("maxDuration", "Workflow duration (seconds)", 3600),
      count("maxDepth", "Maximum delegation depth", 3),
    ],
    servers: [
      name,
      owner,
      {
        key: "endpoint",
        label: "MCP endpoint",
        required: true,
        default: "https://mcp.example.test/mcp",
      },
      choice("transport", "Transport", [
        "Streamable HTTP",
        "SSE compatibility",
      ]),
      choice("auth", "Authentication", [
        "OAuth broker",
        "API key broker",
        "mTLS",
      ]),
      secret,
    ],
    tools: [
      name,
      reference("serverId", "MCP server", "servers"),
      choice("action", "Action class", [
        "READ",
        "CREATE",
        "UPDATE",
        "DELETE",
        "FINANCIAL",
        "PRIVILEGED",
      ]),
      {
        key: "scope",
        label: "Allowed resource or prefix",
        required: true,
        default: "RECORD-*",
      },
      {
        key: "parameters",
        label: "Required argument names",
        type: "multi",
        options: ["claim_id", "vendor_id", "account_ref", "record_id", "query"],
        default: ["record_id"],
      },
      {
        key: "expires",
        label: "Permission expires",
        type: "datetime",
        required: true,
        default: Date.now() + 7 * 86400000,
      },
    ],
    assets: [
      name,
      choice("type", "Asset type", [
        "Application",
        "Agent",
        "Model",
        "MCP server",
        "Tool",
        "Repository",
        "Extension",
      ]),
      owner,
      choice("risk", "Risk", ["Low", "Medium", "High", "Critical"]),
      choice("coverage", "Control coverage", [
        "Governed",
        "Partial",
        "Unprotected",
      ]),
      choice("status", "Lifecycle", [
        "Discovered",
        "Active",
        "Quarantined",
        "Archived",
      ]),
      {
        key: "tags",
        label: "Tags",
        type: "multi",
        options: ["production", "agent", "shadow-ai", "sensitive", "reviewed"],
        default: [],
      },
      {
        key: "links",
        label: "Related objects",
        type: "multi",
        options: [
          ...resourceOptions(state, "projects"),
          ...resourceOptions(state, "agents"),
          ...resourceOptions(state, "routes"),
          ...resourceOptions(state, "policies"),
          ...resourceOptions(state, "budgets"),
        ],
        default: [],
      },
    ],
    workforcePolicies: [
      name,
      choice("instance", "Account instance", [
        "Personal account",
        "Enterprise tenant",
        "Unknown account",
      ]),
      choice("activity", "Activity", [
        "Visit",
        "Prompt",
        "Paste",
        "File upload",
        "Download",
      ]),
      choice("action", "Action", ["Allow", "Coach", "Redact", "Block"]),
      {
        key: "justification",
        label: "Require user justification",
        type: "checkbox",
        default: true,
      },
    ],
    exceptions: [
      name,
      { key: "resource", label: "Resource or incident ID", required: true },
      { key: "scope", label: "Exact exception scope", required: true },
      {
        key: "reason",
        label: "Business justification",
        type: "textarea",
        required: true,
      },
      {
        key: "expires",
        label: "Exception expires",
        type: "datetime",
        required: true,
        default: Date.now() + 86400000,
      },
    ],
    campaigns: [
      name,
      reference("target", "Target application", "projects"),
      choice("pack", "Test pack", [
        "Prompt injection",
        "Data leakage",
        "Tool misuse",
        "Full regression",
      ]),
      choice("schedule", "Schedule", [
        "Manual",
        "Daily",
        "Weekly",
        "CI triggered",
      ]),
      choice("gate", "Release gate", [
        "Block on high severity",
        "Block on any finding",
      ]),
    ],
    scans: [
      name,
      reference("target", "Target application", "projects"),
      {
        key: "artifact",
        label: "Artifact reference",
        required: true,
        default: "registry.example.test/models/claims:v1",
      },
      choice("provenance", "Provenance input", [
        "Signed image",
        "Model manifest",
        "MCP package",
        "Repository revision",
      ]),
      choice("gate", "Release gate", [
        "Block on high severity",
        "Block on any finding",
      ]),
    ],
    integrations: [
      name,
      choice("type", "Integration type", [
        "SIEM webhook",
        "OpenTelemetry",
        "IdP / OIDC",
        "ITSM",
        "DLP connector",
        "Endpoint connector",
      ]),
      {
        key: "endpoint",
        label: "Endpoint",
        required: true,
        default: "https://connector.example.test/events",
      },
      secret,
    ],
    members: [
      name,
      { key: "email", label: "Email address", required: true },
      choice("role", "Role", [
        "Platform admin",
        "Security admin",
        "Governance owner",
        "Platform engineer",
        "Developer",
        "Agent owner",
        "FinOps owner",
        "SOC analyst",
        "Auditor",
      ]),
    ],
  };
  return schemas[collection] || [name];
}
